version: "3.9"
networks:
  default:
    name: kong-net
services:
  kong:
    image: kong:3.1.0-alpine
    hostname: kong
    container_name: kong
    environment:
      KONG_DATABASE: "off"
      KONG_PROXY_ACCESS_LOG: "/dev/stdout"
      KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
      KONG_PROXY_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
      KONG_DECLARATIVE_CONFIG: "/opt/kong/kong.yaml"
    command: "kong start"
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    volumes:
      - ./kong-config:/opt/kong

  users-manager:
    image: users-manager:latest
    hostname: users-manager
    container_name: users-manager
    ports:
      - "4100:4100"

  shipments-manager:
    image: shipments-manager:latest
    hostname: shipments-manager
    container_name: shipments-manager
    ports:
      - "4200:4200"

  restrictions-manager:
    image: restrictions-manager:latest
    hostname: restrictions-manager
    container_name: restrictions-manager
    ports:
      - "4300:4300"

  purchases-manager:
    image: purchases-manager:latest
    hostname: purchases-manager
    container_name: purchases-manager
    ports:
      - "4400:4400"

  payments-manager:
    image: payments-manager:latest
    hostname: payments-manager
    container_name: payments-manager
    ports:
      - "4500:4500"

  levels-manager:
    image: levels-manager:latest
    hostname: levels-manager
    container_name: levels-manager
    ports:
      - "4600:4600"

  ml-app:
    image: ml-app:latest
    hostname: ml-app
    container_name: ml-app
    ports:
      - "8080:8080"
